# Generated by Django 5.2.7 on 2025-10-24 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='editors_pick',
            field=models.BooleanField(default=False),
        ),
    ]
